In [47]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
from sklearn.model_selection import train_test_split
from tensorflow.keras.metrics import R2Score, MeanAbsoluteError, MeanAbsolutePercentageError
import tensorflow_docs as tfdocs
import tensorflow_docs.plots
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os 
from sklearn.preprocessing import StandardScaler

os.environ['CUDA_VISIBLE_DEVICES'] = '-1'

In [28]:
# Charger votre jeu de donn√©es
data = pd.read_csv('C:/Users/utilisateur/2024/E1/data/data.csv')

In [29]:
# Select only numeric columns
numeric_data = data.select_dtypes(include=[np.number])


# Split data into training and testing sets
X_train, X_test = train_test_split(numeric_data, test_size=0.2, random_state=42)

X_test_original = X_test.copy()

# Introduce missing values in 10% of the test data
np.random.seed(42)
mask = np.random.rand(*X_test.shape) < 0.1
X_test[mask] = np.nan

In [30]:
X_test_original.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2555 entries, 1516 to 565
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        2555 non-null   int64
 1   Price                     2555 non-null   int64
 2   Levy                      2555 non-null   int64
 3   Engine volume             2555 non-null   float64
 4   Mileage(km)               2555 non-null   int64
 5   Cylinders                 2555 non-null   float64
 6   Airbags                   2555 non-null   int64
 7   Fuel type_CNG             2555 non-null   int64
 8   Fuel type_Diesel          2555 non-null   int64
 9   Fuel type_Hybrid          2555 non-null   int64
 10  Fuel type_Hydrogen        2555 non-null   int64
 11  Fuel type_LPG             2555 non-null   int64
 12  Fuel type_Petrol          2555 non-null   int64
 13  Fuel type_Plug-in Hybrid  2555 non-null   int64
dtypes: float64(2), int64(12)
memory usage: 299.4 KB

In [31]:
# Initialize the StandardScaler
scaler = StandardScaler()

# Fit the scaler on the training data and transform both training and testing data
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train_scaled = pd.DataFrame(X_train_scaled, columns=X_train.columns)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=X_test.columns)


# The resulting X_train_scaled and X_test_scaled are now normalized versions of the original data
X_train_scaled, X_test_scaled

(             ID     Price      Levy  Engine volume  Mileage(km)  Cylinders  \
 0      0.184436  1.347704  0.325234       0.243656    -0.030832  -0.482835
 1      0.241940 -0.532589 -1.023591       0.243656    -0.031848  -0.482835
 2      0.254563 -0.433286 -1.023591      -0.870033    -0.032765  -0.482835
 3      0.269480 -0.661765  0.332178       0.243656    -0.031626  -0.482835
 4      0.225258 -1.252688  3.238141       2.693771    -0.030441   2.884487
 ...         ...       ...       ...            ...          ...        ...
 10212 -0.313660 -0.465971 -1.023591       0.243656    -0.030810  -0.482835
 10213  0.253813 -0.041593  0.297459      -0.535927    -0.032439  -0.482835
 10214  0.247376 -0.139543 -1.023591      -1.092771    -0.031930  -0.482835
 10215  0.248555  1.166274  0.332178       0.243656    -0.033030  -0.482835
 10216  0.251160 -1.272673 -1.023591       0.243656    -0.034883  -0.482835

         Airbags  Fuel type_CNG  Fuel type_Diesel  Fuel type_Hybrid  \
 0     -0.679985      -0.164440          2.371879         -0.584094
 1     -0.679985       6.081234         -0.421607         -0.584094
 2     -1.133783      -0.164440         -0.421607         -0.584094
 3      1.135204      -0.164440         -0.421607         -0.584094
 4     -1.587580      -0.164440         -0.421607         -0.584094
 ...         ...            ...               ...               ...
 10212 -1.587580      -0.164440          2.371879         -0.584094
 10213 -0.226188      -0.164440         -0.421607         -0.584094
 10214 -1.133783      -0.164440         -0.421607         -0.584094
 10215  0.681407      -0.164440         -0.421607         -0.584094
 10216 -1.587580      -0.164440         -0.421607         -0.584094

        Fuel type_Hydrogen  Fuel type_LPG  Fuel type_Petrol  \
 0               -0.009894      -0.133917         -1.097196
 1               -0.009894      -0.133917         -1.097196
 2               -0.009894      -0.133917          0.911414
 3               -0.009894      -0.133917          0.911414
 4               -0.009894      -0.133917          0.911414
 ...                   ...            ...               ...
 10212           -0.009894      -0.133917         -1.097196
 10213           -0.009894      -0.133917          0.911414
 10214           -0.009894      -0.133917          0.911414
 10215           -0.009894      -0.133917          0.911414
 10216           -0.009894      -0.133917          0.911414

        Fuel type_Plug-in Hybrid
 0                     -0.066512
 1                     -0.066512
 2                     -0.066512
 3                     -0.066512
 4                     -0.066512
 ...                         ...
 10212                 -0.066512
 10213                 -0.066512
 10214                 -0.066512
 10215                 -0.066512
 10216                 -0.066512

 [10217 rows x 14 columns],
             ID     Price      Levy  Engine volume  Mileage(km)  Cylinders  \
 0     0.101057 -0.759715  1.404989       1.357344    -0.031477   1.200826
 1     0.270558 -0.971955  0.280100       0.132287    -0.030976  -0.482835
 2     0.219931       NaN  1.404989       1.357344          NaN   1.200826
 3          NaN -1.249357  3.160024       4.364304    -0.029287   2.884487
 4          NaN -1.274755       NaN      -0.535927    -0.033865   1.200826
 ...        ...       ...       ...            ...          ...        ...
 2550 -0.045075  0.578683  0.276628       0.132287          NaN  -0.482835
 2551  0.218112  1.819131  0.804354       1.357344    -0.030422   1.200826
 2552       NaN  1.655916  0.203718      -0.313189    -0.030810  -0.482835
 2553  0.265711 -1.208553       NaN       0.132287    -0.029269  -0.482835
 2554 -2.629488  0.480733  0.332178      -0.981402    -0.034571  -0.482835

        Airbags  Fuel type_CNG  Fuel type_Diesel  Fuel type_Hybrid  \
 0          NaN       -0.16444         -0.421607          1.712054
 1     1.135204       -0.16444         -0.421607         -0.584094
 2     1.135204       -0.16444          2.371879               NaN
 3     1.135204       -0.16444         -0.421607         -0.584094
 4     0.227609       -0.16444         -0.421607         -0.584094
 ...        ...            ...               ...               ...
 2550  0.227609       -0.16444         -0.421607         -0.584094
 2551  1.135204       -0.16444          2.371879         -0.584094
 2552 -1.587580       -0.16444         -0.421607         -0.584094
 2553  1.135204       -0.16444         -0.421607          1.712054
 2554  0.227609       -0.16444         -0.421607         -0.584094

       Fuel type_Hydrogen  Fuel type_LPG  Fuel type_Petrol  \
 0                    NaN      -0.133917         -1.097196
 1              -0.009894      -0.133917          0.911414
 2              -0.009894      -0.133917         -1.097196
 3              -0.009894      -0.133917          0.911414
 4              -0.009894      -0.133917               NaN
 ...                  ...            ...               ...
 2550           -0.009894      -0.133917          0.911414
 2551           -0.009894      -0.133917         -1.097196
 2552           -0.009894      -0.133917          0.911414
 2553           -0.009894      -0.133917         -1.097196
 2554           -0.009894      -0.133917               NaN

       Fuel type_Plug-in Hybrid
 0                    -0.066512
 1                    -0.066512
 2                    -0.066512
 3                    -0.066512
 4                    -0.066512
 ...                        ...
 2550                 -0.066512
 2551                 -0.066512
 2552                 -0.066512
 2553                 -0.066512
 2554                 -0.066512

 [2555 rows x 14 columns])

In [32]:
# Confirm that missing values were introduced
print("Missing values in X_test:", X_test.isna().sum().sum())

Missing values in X_test: 3589

In [33]:
print("values in X_test:", X_test.notna().sum().sum())

values in X_test: 32181

In [60]:

class CustomImputerModel:
    def __init__(self):
        self.models = {}
        self.column_types = {}  # Pour stocker les types de chaque colonne
        self.min_values = {}    # Pour stocker les valeurs minimales
        self.max_values = {}    # Pour stocker les valeurs maximales

    def fit(self, X_ref, X_train):
        # Utiliser X_ref pour r√©cup√©rer les types de colonnes, min et max
        for col in X_ref.columns:
            self.column_types[col] = X_ref[col].dtype
            self.min_values[col] = X_ref[col].min()
            self.max_values[col] = X_ref[col].max()

        # Utiliser X_train pour l'entra√Ænement
        for col in X_train.columns:
            features = X_train.drop(col, axis=1)
            target = X_train[col]

            non_missing = target.notna()
            features_non_missing = features[non_missing]
            target_non_missing = target[non_missing]

            # Cr√©er un mod√®le de r√©seau de neurones simple
            model = Sequential([
                Input(shape=(features_non_missing.shape[1],)),
                Dense(128, activation='relu'),
                Dense(128, activation='relu'),
                Dense(64, activation='relu'),
                Dense(1)
            ])
            model.compile(optimizer='adam', loss='mean_squared_error',metrics=[R2Score(), MeanAbsolutePercentageError(), MeanAbsoluteError()])

            # Entra√Æner le mod√®le
            model.fit(features_non_missing, target_non_missing, epochs=50, batch_size=32, verbose=0)
            self.models[col] = model
            history = model.fit(features_non_missing, target_non_missing, epochs=50, batch_size=32, verbose=0, validation_split=0.2)
        return history
    
    def predict(self, X):
        X_imputed = X.copy()

        for col in X.columns:
            missing = X_imputed[col].isna()
            if missing.any():
                X_missing = X_imputed[missing].drop(col, axis=1)
                predictions = self.models[col].predict(X_missing).flatten()

                # Convertir les pr√©dictions au type original
                if self.column_types[col].kind in ['i', 'u']:
                    predictions = np.round(predictions).astype(self.column_types[col])
                elif self.column_types[col].kind == 'f':
                    predictions = predictions.astype(self.column_types[col])
                
                # Limiter les pr√©dictions aux plages de valeurs minimales et maximales
                predictions = np.clip(predictions, self.min_values[col], self.max_values[col])

                # Assurer que toutes les valeurs sont positives pour les types num√©riques
                if self.column_types[col].kind in ['i', 'u', 'f']:
                    predictions = np.maximum(predictions, 0)

                X_imputed.loc[missing, col] = predictions

        return X_imputed

In [ ]:
# Initialize and fit the custom model
model = CustomImputerModel()
model.fit(numeric_data, X_train_scaled)

In [ ]:
history = model.fit(numeric_data, X_train_scaled)

In [ ]:
size_histories = {}  # Dictionnaire pour stocker les historiques

size_histories['config']= history
history.history

In [ ]:
import matplotlib.pyplot as plt

def plot_learning_curves(history):
    loss = history.history['loss']
    val_loss = history.history.get('val_loss', None)

    epochs = range(1, len(loss) + 1)

    plt.plot(epochs, loss, 'bo', label='Training loss')
    if val_loss is not None:
        plt.plot(epochs, val_loss, 'b', label='Validation loss')
    plt.title('Learning curve')
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend()

    plt.show()

In [23]:
from joblib import dump

# Supposons que `model` est votre mod√®le entra√Æn√©
dump(imputer_model, 'C:/Users/utilisateur/2024/models/model.joblib')

['C:/Users/utilisateur/2024/models/model.joblib']

In [ ]:
# Impute missing values in the test set
X_test_imputed = imputer_model.predict(X_test)

# Show the first few rows of the imputed test set
X_test_imputed.head()

9/9 [==============================] - 0s 2ms/step
9/9 [==============================] - 0s 2ms/step
1/8 [==>...........................] - ETA: 0s

/tmp/ipykernel_58686/3201796851.py:53: RuntimeWarning: invalid value encountered in cast
  predictions = np.round(predictions).astype(self.column_types[col])
/tmp/ipykernel_58686/3201796851.py:53: RuntimeWarning: invalid value encountered in cast
  predictions = np.round(predictions).astype(self.column_types[col])

8/8 [==============================] - 0s 2ms/step
9/9 [==============================] - 0s 2ms/step
8/8 [==============================] - 0s 2ms/step

/tmp/ipykernel_58686/3201796851.py:53: RuntimeWarning: invalid value encountered in cast
  predictions = np.round(predictions).astype(self.column_types[col])
/tmp/ipykernel_58686/3201796851.py:53: RuntimeWarning: invalid value encountered in cast
  predictions = np.round(predictions).astype(self.column_types[col])

9/9 [==============================] - 0s 2ms/step
8/8 [==============================] - 0s 2ms/step
9/9 [==============================] - 0s 2ms/step
9/9 [==============================] - 0s 2ms/step

/tmp/ipykernel_58686/3201796851.py:53: RuntimeWarning: invalid value encountered in cast
  predictions = np.round(predictions).astype(self.column_types[col])
/tmp/ipykernel_58686/3201796851.py:53: RuntimeWarning: invalid value encountered in cast
  predictions = np.round(predictions).astype(self.column_types[col])
/tmp/ipykernel_58686/3201796851.py:53: RuntimeWarning: invalid value encountered in cast
  predictions = np.round(predictions).astype(self.column_types[col])

8/8 [==============================] - 0s 2ms/step
9/9 [==============================] - 0s 2ms/step
8/8 [==============================] - 0s 2ms/step

/tmp/ipykernel_58686/3201796851.py:53: RuntimeWarning: invalid value encountered in cast
  predictions = np.round(predictions).astype(self.column_types[col])
/tmp/ipykernel_58686/3201796851.py:53: RuntimeWarning: invalid value encountered in cast
  predictions = np.round(predictions).astype(self.column_types[col])
/tmp/ipykernel_58686/3201796851.py:53: RuntimeWarning: invalid value encountered in cast
  predictions = np.round(predictions).astype(self.column_types[col])

8/8 [==============================] - 0s 2ms/step
9/9 [==============================] - 0s 2ms/step

/tmp/ipykernel_58686/3201796851.py:53: RuntimeWarning: invalid value encountered in cast
  predictions = np.round(predictions).astype(self.column_types[col])
/tmp/ipykernel_58686/3201796851.py:53: RuntimeWarning: invalid value encountered in cast
  predictions = np.round(predictions).astype(self.column_types[col])

,ID,Price,Levy,Engine volume,Mileage(km),Cylinders,Airbags,Fuel type_CNG,Fuel type_Diesel,Fuel type_Hybrid,Fuel type_Hydrogen,Fuel type_LPG,Fuel type_Petrol,Fuel type_Plug-in Hybrid
1516,45649679.0,5018.0,1399.0,3.5,167222.0,6.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
2420,45815912.0,2979.0,751.0,2.4,191848.0,4.0,12.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
9726,45766261.0,1.0,1399.0,3.5,0.0,6.0,12.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
1372,45816654.0,314.0,2410.0,6.2,274771.0,8.0,12.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
8296,20746880.0,70.0,0.0,1.8,50000.0,6.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
X_test_imputed = scaler.inverse_transform(X_test_imputed)
X_test_imputed = pd.DataFrame(X_test_imputed, columns=X_test.columns)

In [ ]:
 X_test_imputed

,ID,Price,Levy,Engine volume,Mileage(km),Cylinders,Airbags,Fuel type_CNG,Fuel type_Diesel,Fuel type_Hybrid,Fuel type_Hydrogen,Fuel type_LPG,Fuel type_Petrol,Fuel type_Plug-in Hybrid
1516,45649679.0,5018.0,1399.0,3.5,167222.0,6.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
2420,45815912.0,2979.0,751.0,2.4,191848.0,4.0,12.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
9726,45766261.0,1.0,1399.0,3.5,0.0,6.0,12.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
1372,45816654.0,314.0,2410.0,6.2,274771.0,8.0,12.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
8296,20746880.0,70.0,0.0,1.8,50000.0,6.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4115,45506364.0,17876.0,749.0,2.4,2111669.0,4.0,8.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
9572,45764477.0,29793.0,1053.0,3.5,219030.0,6.0,12.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
6315,45816654.0,28225.0,707.0,2.0,200000.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
7666,45811158.0,706.0,135.0,2.4,275654.0,4.0,12.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
565,42971782.0,16935.0,781.0,1.4,15333.0,4.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# Debugging: Check for NaN values after imputation
nan_count_after = X_test_imputed.isna().sum().sum()
print("NaN count after imputation:", nan_count_after)

NaN count after imputation: 347

In [ ]:
perc=  ((3589-nan_count_after)*100)/3589
perc

90.33156868208414

In [ ]:
comp = X_test_origine.compare(X_test_imputed)

In [ ]:
comp.head(50)

        ID             Price       Levy        Engine volume        \
      self       other  self other self  other          self other
1516   NaN         NaN   NaN   NaN  NaN    NaN           NaN   NaN
9726   NaN         NaN   NaN   1.0  NaN    NaN           NaN   NaN
1372   NaN  45816654.0   NaN   NaN  NaN    NaN           NaN   NaN
8296   NaN  20746880.0   NaN   NaN  NaN    0.0           NaN   NaN
6560   NaN         NaN   NaN   NaN  NaN    0.0           NaN   NaN
5635   NaN  20746880.0   NaN   NaN  NaN    0.0           NaN   NaN
3877   NaN         NaN   NaN   NaN  NaN  437.0           NaN   NaN
10983  NaN         NaN   NaN   NaN  NaN    NaN           NaN   NaN
6618   NaN         NaN   NaN   NaN  NaN    NaN           NaN   NaN
9132   NaN  20746880.0   NaN   NaN  NaN    NaN           NaN   0.1
9624   NaN         NaN   NaN   NaN  NaN    NaN           NaN   NaN
3613   NaN         NaN   NaN   NaN  NaN    NaN           NaN   NaN
10691  NaN         NaN   NaN   NaN  NaN    NaN           NaN   NaN
9500   NaN         NaN   NaN   NaN  NaN    NaN           NaN   NaN
9112   NaN         NaN   NaN   NaN  NaN    NaN           NaN   NaN
5220   NaN         NaN   NaN   NaN  NaN    NaN           NaN   NaN
518    NaN         NaN   NaN   NaN  NaN    NaN           NaN   NaN
8723   NaN         NaN   NaN   NaN  NaN    NaN           NaN   NaN
5007   NaN         NaN   NaN   NaN  NaN    NaN           NaN   NaN
12619  NaN         NaN   NaN   NaN  NaN    NaN           NaN   NaN
11089  NaN         NaN   NaN   NaN  NaN    NaN           NaN   NaN
4667   NaN         NaN   NaN   NaN  NaN    NaN           NaN   NaN
1807   NaN         NaN   NaN   NaN  NaN    NaN           NaN   NaN
10282  NaN         NaN   NaN   1.0  NaN    NaN           NaN   0.1
9743   NaN         NaN   NaN   NaN  NaN    0.0           NaN   NaN
4339   NaN  20746880.0   NaN   NaN  NaN    0.0           NaN   NaN
7322   NaN         NaN   NaN   1.0  NaN    NaN           NaN   NaN
12553  NaN         NaN   NaN   NaN  NaN    NaN           NaN   NaN
6503   NaN  20746880.0   NaN   NaN  NaN    NaN           NaN   NaN
3499   NaN         NaN   NaN   NaN  NaN    NaN           NaN   NaN
4176   NaN         NaN   NaN   NaN  NaN    NaN           NaN   NaN
6455   NaN         NaN   NaN   NaN  NaN    NaN           NaN   NaN
6428   NaN         NaN   NaN   NaN  NaN    NaN           NaN   NaN
11135  NaN         NaN   NaN   NaN  NaN    NaN           NaN   7.3
9265   NaN         NaN   NaN   NaN  NaN    NaN           NaN   NaN
12691  NaN         NaN   NaN   NaN  NaN    NaN           NaN   NaN
357    NaN         NaN   NaN   1.0  NaN    NaN           NaN   NaN
7624   NaN  20746880.0   NaN   NaN  NaN    NaN           NaN   NaN
12050  NaN         NaN   NaN   NaN  NaN    NaN           NaN   NaN
2417   NaN         NaN   NaN   NaN  NaN    NaN           NaN   NaN
3615   NaN  44467596.0   NaN   NaN  NaN    NaN           NaN   NaN
8558   NaN         NaN   NaN   1.0  NaN    NaN           NaN   NaN
2392   NaN         NaN   NaN   NaN  NaN    NaN           NaN   NaN
6594   NaN         NaN   NaN   NaN  NaN    NaN           NaN   NaN
839    NaN         NaN   NaN   NaN  NaN    NaN           NaN   NaN
3694   NaN         NaN   NaN   NaN  NaN    NaN           NaN   NaN
1945   NaN  20746880.0   NaN   NaN  NaN    NaN           NaN   NaN
11744  NaN         NaN   NaN   NaN  NaN    0.0           NaN   NaN
811    NaN         NaN   NaN   NaN  NaN    NaN           NaN   NaN
8046   NaN  20746880.0   NaN   NaN  NaN    NaN           NaN   NaN

      Mileage(km)             ... Fuel type_Hybrid       Fuel type_Hydrogen  \
             self      other  ...             self other               self
1516          NaN        NaN  ...              NaN   NaN                NaN
9726          NaN        0.0  ...              NaN   1.0                NaN
1372          NaN        NaN  ...              NaN   NaN                NaN
8296          NaN        NaN  ...              NaN   NaN                NaN
6560          NaN        NaN  ...              NaN   NaN                NaN
5635          NaN        NaN  ...              NaN   NaN                NaN
3877          NaN        NaN  ...              NaN   NaN                NaN
10983         NaN        NaN  ...              NaN   NaN                NaN
6618          NaN        NaN  ...              NaN   NaN                NaN
9132          NaN        NaN  ...              NaN   NaN                NaN
9624          NaN        NaN  ...              NaN   NaN                NaN
3613          NaN        NaN  ...              NaN   0.0                NaN
10691         NaN        NaN  ...              NaN   NaN                NaN
9500          NaN        NaN  ...              NaN   NaN                NaN
9112          NaN        NaN  ...              NaN   NaN                NaN
5220          NaN        NaN  ...              NaN   NaN                NaN
518           NaN        NaN  ...              NaN   NaN                NaN
8723          NaN        NaN  ...              NaN   NaN                NaN
5007          NaN        0.0  ...              NaN   NaN                NaN
12619         NaN        NaN  ...              NaN   NaN                NaN
11089         NaN        NaN  ...              NaN   NaN                NaN
4667          NaN        0.0  ...              NaN   NaN                NaN
1807          NaN        NaN  ...              NaN   NaN                NaN
10282         NaN        NaN  ...              NaN   NaN                NaN
9743          NaN  2113426.0  ...              NaN   NaN                NaN
4339          NaN        NaN  ...              NaN   NaN                NaN
7322          NaN        NaN  ...              NaN   NaN                NaN
12553         NaN        NaN  ...              NaN   NaN                NaN
6503          NaN        NaN  ...              NaN   NaN                NaN
3499          NaN        NaN  ...              NaN   NaN                NaN
4176          NaN        NaN  ...              NaN   NaN                NaN
6455          NaN        NaN  ...              NaN   NaN                NaN
6428          NaN        NaN  ...              NaN   NaN                NaN
11135         NaN        NaN  ...              NaN   NaN                NaN
9265          NaN        NaN  ...              NaN   NaN                NaN
12691         NaN        NaN  ...              NaN   NaN                NaN
357           NaN        NaN  ...              NaN   NaN                NaN
7624          NaN        NaN  ...              NaN   NaN                NaN
12050         NaN        NaN  ...              NaN   NaN                NaN
2417          NaN        NaN  ...              NaN   NaN                NaN
3615          NaN        NaN  ...              NaN   NaN                NaN
8558          NaN  2057169.0  ...              NaN   NaN                NaN
2392          NaN        NaN  ...              NaN   NaN                NaN
6594          NaN        NaN  ...              NaN   NaN                NaN
839           NaN        NaN  ...              NaN   NaN                NaN
3694          NaN        NaN  ...              NaN   1.0                NaN
1945          NaN        NaN  ...              NaN   NaN                NaN
11744         NaN        NaN  ...              NaN   NaN                NaN
811           NaN        NaN  ...              NaN   NaN                NaN
8046          NaN        NaN  ...              NaN   NaN                NaN

            Fuel type_LPG       Fuel type_Petrol        \
      other          self other             self other
1516    1.0           NaN   NaN              NaN   NaN
9726    NaN           NaN   NaN              NaN   NaN
1372    NaN           NaN   NaN              NaN   NaN
8296    NaN           NaN   NaN              NaN   0.0
6560    NaN           NaN   NaN              NaN   NaN
5635    NaN           NaN   0.0              NaN   NaN
3877    NaN           NaN   NaN              NaN   NaN
10983   NaN           NaN   NaN              NaN   NaN
6618    1.0           NaN   NaN              NaN   NaN
9132    NaN           NaN   NaN              NaN   NaN
9624    NaN           NaN   NaN              NaN   NaN
3613    NaN           NaN   NaN              NaN   0.0
10691   NaN           NaN   NaN              NaN   0.0
9500    NaN           NaN   NaN              NaN   NaN
9112    NaN           NaN   NaN              NaN   NaN
5220    NaN           NaN   NaN              NaN   NaN
518     0.0           NaN   0.0              NaN   NaN
8723    NaN           NaN   NaN              NaN   NaN
5007    NaN           NaN   NaN              NaN   NaN
12619   0.0           NaN   NaN              NaN   0.0
11089   NaN           NaN   0.0              NaN   NaN
4667    NaN           NaN   NaN              NaN   NaN
1807    0.0           NaN   NaN              NaN   NaN
10282   NaN           NaN   NaN              NaN   NaN
9743    NaN           NaN   NaN              NaN   NaN
4339    NaN           NaN   NaN              NaN   NaN
7322    1.0           NaN   NaN              NaN   NaN
12553   1.0           NaN   NaN              NaN   NaN
6503    1.0           NaN   NaN              NaN   NaN
3499    NaN           NaN   NaN              NaN   NaN
4176    0.0           NaN   0.0              NaN   NaN
6455    1.0           NaN   NaN              NaN   NaN
6428    NaN           NaN   0.0              NaN   NaN
11135   NaN           NaN   NaN              NaN   NaN
9265    NaN           NaN   NaN              NaN   0.0
12691   NaN           NaN   0.0              NaN   NaN
357     NaN           NaN   0.0              NaN   NaN
7624    NaN           NaN   NaN              NaN   0.0
12050   1.0           NaN   NaN              NaN   NaN
2417    NaN           NaN   NaN              NaN   NaN
3615    NaN           NaN   NaN              NaN   NaN
8558    NaN           NaN   NaN              NaN   NaN
2392    NaN           NaN   NaN              NaN   NaN
6594    NaN           NaN   NaN              NaN   NaN
839     1.0           NaN   NaN              NaN   NaN
3694    NaN           NaN   NaN              NaN   NaN
1945    1.0           NaN   NaN              NaN   NaN
11744   NaN           NaN   NaN              NaN   NaN
811     1.0           NaN   NaN              NaN   NaN
8046    NaN           NaN   NaN              NaN   NaN

      Fuel type_Plug-in Hybrid
                          self other
1516                       NaN   NaN
9726                       NaN   NaN
1372                       NaN   NaN
8296                       NaN   NaN
6560                       NaN   0.0
5635                       NaN   NaN
3877                       NaN   NaN
10983                      NaN   NaN
6618                       NaN   NaN
9132                       NaN   NaN
9624                       NaN   NaN
3613                       NaN   NaN
10691                      NaN   NaN
9500                       NaN   0.0
9112                       NaN   NaN
5220                       NaN   NaN
518                        NaN   NaN
8723                       NaN   NaN
5007                       NaN   NaN
12619                      NaN   0.0
11089                      NaN   NaN
4667                       NaN   NaN
1807                       NaN   0.0
10282                      NaN   NaN
9743                       NaN   NaN
4339                       NaN   NaN
7322                       NaN   NaN
12553                      NaN   NaN
6503                       NaN   NaN
3499                       NaN   NaN
4176                       NaN   NaN
6455                       NaN   NaN
6428                       NaN   NaN
11135                      NaN   NaN
9265                       NaN   NaN
12691                      NaN   NaN
357                        NaN   NaN
7624                       NaN   NaN
12050                      NaN   NaN
2417                       NaN   NaN
3615                       NaN   NaN
8558                       NaN   NaN
2392                       NaN   NaN
6594                       NaN   NaN
839                        NaN   NaN
3694                       NaN   NaN
1945                       NaN   NaN
11744                      NaN   NaN
811                        NaN   NaN
8046                       NaN   NaN

[50 rows x 28 columns]